"""Windows Electron acceptance: real packaged app, IPC, sidecar and Bandit.
Requires playwright in the build Python; no browser installation necessary.
"""
import os,sys,time,json,subprocess,urllib.request,sqlite3,base64,zipfile,io
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
expect.set_options(timeout=45000)
root=Path(os.environ['LOCALAPPDATA'])/'SentinelBuild'
output=root/'screenshots-workbench';output.mkdir(exist_ok=True)
env=dict(os.environ,SXF_DATA_DIR=str(root/'workbench-test-data'),SXF_WORKBENCH_PROFILE=str(root/'workbench-test-profile'))
with sqlite3.connect(Path(os.environ['LOCALAPPDATA'])/'Sentinel/data/sentinel.db') as c:
 projects=[json.loads(r[0]) for r in c.execute('SELECT payload FROM projects')]
pikachu=next((p for p in projects if p['name'].lower()=='pikachu'),None)
if pikachu:env['SXF_REPO_ROOTS']=os.pathsep.join([pikachu['path'],str(root/'workbench-test-data/repositories'),str(root/'workbench-release/DoublePupil/resources/backend/_internal/demo')])
exe=root/'workbench-release/DoublePupil/DoublePupil.exe'
proc=subprocess.Popen([str(exe),'--remote-debugging-port=9234'],env=env,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
result={'steps':[]};errors=[]
try:
 for _ in range(150):
  try:
   urllib.request.urlopen('http://127.0.0.1:9234/json/version',timeout=1);break
  except Exception:time.sleep(.2)
 if True:
  p=sync_playwright().start()
  browser=p.chromium.connect_over_cdp('http://127.0.0.1:9234')
  context=browser.contexts[0]
  page=context.pages[0] if context.pages else context.wait_for_event('page',timeout=30000)
  page.set_default_timeout(45000)
  page.on('pageerror',lambda e:errors.append(str(e)))
  expect(page.get_by_role('heading',name='安全态势总览')).to_be_visible()
  page.screenshot(path=str(output/'01-overview.png'));result['steps'].append('Packaged Electron starts bundled non-Qt Python backend and reads dashboard')
  expect(page.get_by_text('Double Pupil',exact=True)).to_be_visible()
  page.get_by_role('button',name='资产',exact=True).click()
  expect(page.get_by_role('heading',name='资产拓扑',exact=True)).to_be_visible()
  expect(page.get_by_role('heading',name='资产登记',exact=True)).to_have_count(0)
  page.get_by_role('button',name='新增资产',exact=True).click()
  expect(page.get_by_role('heading',name='资产登记',exact=True)).to_be_visible()
  page.get_by_label('资产名称',exact=True).fill('验收资产')
  page.get_by_label('主机 IP / 域名',exact=True).fill('192.0.2.100')
  page.get_by_label('负责人',exact=True).fill('测试负责人')
  page.get_by_role('button',name='保存资产',exact=True).click()
  expect(page.get_by_role('heading',name='资产拓扑',exact=True)).to_be_visible()
  expect(page.locator('.react-flow__node').filter(has_text='验收资产')).to_have_count(1)
  page.get_by_role('button',name='编辑资产',exact=True).click()
  page.get_by_label('负责人',exact=True).fill('更新负责人')
  page.get_by_role('button',name='保存资产',exact=True).click()
  expect(page.get_by_role('button',name='编辑资产',exact=True)).to_be_visible()
  page.get_by_role('button',name='测试 SSH 连接',exact=True).click()
  expect(page.get_by_role('alert')).to_contain_text('请配置 SSH')
  page.get_by_label('关闭提示').click()
  page.screenshot(path=str(output/'07-assets.png'))
  page.get_by_role('button',name='删除',exact=True).click()
  page.get_by_role('button',name='确认删除资产',exact=True).click()
  expect(page.locator('.react-flow__node').filter(has_text='验收资产')).to_have_count(0)
  page.get_by_role('button',name='发现内网资产',exact=True).click()
  page.get_by_label('发现目标').fill('172.20.0.252/32')
  page.get_by_label('发现端口').fill('80,8080,8081')
  page.get_by_role('button',name='开始发现并入库',exact=True).click()
  expect(page.get_by_text('completed · 已检查 1/1 · 发现 1 台',exact=True)).to_be_visible()
  expect(page.locator('.react-flow__node').filter(has_text='172.20.0.252')).to_have_count(1)
  page.screenshot(path=str(output/'09-topology-discovery.png'))
  result['steps'].append('Asset topology default, registration only on New, CRUD, real single-host RFC1918 TCP discovery')
  expect(page.get_by_role('button',name='智能体',exact=True)).to_have_count(0)
  page.get_by_role('button',name='设置',exact=True).click()
  expect(page.get_by_label('llm.model')).to_be_visible()
  page.get_by_role('button',name='Skills / RAG / 修复',exact=True).click()
  page.get_by_label('名称',exact=True).fill('安全审查 Skill')
  page.get_by_label('内容',exact=True).fill('分析 SQL 注入时引用证据 ID；不可把静态关联当作利用成功。')
  page.get_by_role('button',name='保存配置',exact=True).click()
  expect(page.get_by_text('已保存；下一次调查生效',exact=True)).to_be_visible()
  page.get_by_role('button',name='RAG 知识库',exact=True).click()
  page.get_by_label('名称',exact=True).fill('SQL 修复知识')
  page.get_by_label('内容',exact=True).fill('SQL Injection 注入应使用参数化查询，验证用户参数不能改变 SQL 语义。')
  page.get_by_role('button',name='保存配置',exact=True).click()
  expect(page.get_by_text('已保存；下一次调查生效',exact=True)).to_be_visible()
  page.get_by_placeholder('例如 SQL 注入 参数化查询').fill('SQL 注入')
  page.get_by_role('button',name='检索',exact=True).click()
  expect(page.locator('.json')).to_contain_text('SQL 修复知识')
  page.screenshot(path=str(output/'08-agent-rag.png'))
  result['steps'].append('Skill save and local RAG document save/retrieval through desktop UI')
  page.get_by_role('button',name='事件',exact=True).click()
  search=page.get_by_placeholder('搜索事件、资产、攻击类型…');search.fill('SQL')
  expect(page.locator('tbody tr')).to_have_count(2);search.fill('');expect(page.locator('tbody tr')).to_have_count(6)
  page.locator('tbody tr').filter(has_text='SQL 注入攻击 · 用户查询接口').click()
  page.get_by_label('关联代码项目').select_option('demo-shop')
  page.get_by_role('button',name='AI Investigation',exact=True).click()
  expect(page.locator('.react-flow__node')).to_have_count(4)
  expect(page.get_by_text('CWE-89',exact=True)).to_be_visible()
  page.locator('.react-flow__node').filter(has_text='user_controller').click()
  expect(page.locator('.inspector .code').first).to_contain_text('def user_controller')
  page.locator('.react-flow__node').filter(has_text='find_user').click()
  result['steps'].append('Event search, project binding, real Bandit SQL investigation, 4-node graph and selected function snapshot')
  page.get_by_label('外观主题').select_option('dark');expect(page.locator('html')).to_have_class('dark')
  page.screenshot(path=str(output/'02-canvas-dark.png'))
  page.locator('.evidence-item').first.click();expect(page.locator('.json')).to_be_visible();page.screenshot(path=str(output/'03-evidence.png'))
  report=page.evaluate("""async()=>{const jobs=await window.desktop.request('/investigations');const j=jobs.find(x=>x.event.id==='demo-001'&&x.status==='completed');return await window.desktop.request('/investigations/'+j.id+'/report')}""")
  assert 'CWE-89' in report;(output/'demo-report.md').write_text(report,encoding='utf-8')
  result['steps'].append('Evidence inspector and Markdown report content over restricted IPC')
  refs=page.evaluate("async()=>{const js=await window.desktop.request('/investigations');const j=await window.desktop.request('/investigations/'+js.find(x=>x.event.id==='demo-001'&&x.status==='completed').id);return j.agent_context}")
  assert refs['skills'] and refs['knowledge']
  result['steps'].append('Enabled Skills and cited RAG chunks reach actual investigation context')
  page.get_by_role('button',name='代码',exact=True).click();page.get_by_label('代码项目').select_option('demo-shop')
  page.get_by_role('button',name='运行扫描',exact=True).click();expect(page.get_by_role('button',name='运行扫描',exact=True)).to_be_enabled()
  page.locator('tbody tr').filter(has_text='B608').click();expect(page.locator('.code-selected')).to_have_count(1)
  page.get_by_label('外观主题').select_option('light');expect(page.locator('html')).not_to_have_class('dark');page.screenshot(path=str(output/'04-code-light.png'))
  result['steps'].append('Static code audit, immutable finding snapshot, light and dark mode')
  page.get_by_role('button',name='设置',exact=True).click();page.get_by_role('button',name='XDR 平台',exact=True).click();expect(page.get_by_label('xdr.auth_type')).to_be_visible()
  page.get_by_role('button',name='保存配置',exact=True).click();expect(page.get_by_text('配置已保存',exact=True)).to_be_visible()
  page.screenshot(path=str(output/'05-settings.png'))
  result['steps'].append('Settings load/save, credentials masked and preserved')
  page.get_by_role('button',name='事件',exact=True).click();page.locator('tbody tr').filter(has_text='SQL 注入探测 · 健康检查接口').click();page.get_by_label('关联代码项目').select_option('demo-shop');page.get_by_role('button',name='AI Investigation',exact=True).click()
  expect(page.get_by_role('heading',name='证据不足，未建立漏洞关联')).to_be_visible();expect(page.locator('.react-flow__node')).to_have_count(0)
  result['steps'].append('Negative health endpoint does not invent a vulnerable graph')
  page.get_by_role('button',name='事件',exact=True).click();page.locator('tbody tr').filter(has_text='系统命令注入 · 运维诊断接口').click();page.get_by_label('关联代码项目').select_option('demo-shop');page.get_by_role('button',name='AI Investigation',exact=True).click();expect(page.get_by_text('CWE-78',exact=True)).to_be_visible()
  result['steps'].append('Command injection maps to actual shell=True finding')
  page.get_by_role('button',name='态势',exact=True).click();expect(page.get_by_role('heading',name='安全态势总览')).to_be_visible();page.screenshot(path=str(output/'06-overview-light.png'))
  page.get_by_label('外观主题').select_option('system');page.emulate_media(color_scheme='dark');expect(page.locator('html')).to_have_class('dark');page.emulate_media(color_scheme='light');expect(page.locator('html')).not_to_have_class('dark')
  assert page.evaluate("localStorage.getItem('sentinel-workbench-theme')")=='system'
  result['steps'].append('System color-scheme changes and persisted theme preference')
  assert not errors,errors
  # Renderer cannot access Node, navigate away, or request arbitrary API routes.
  assert page.evaluate("typeof require")=='undefined'
  rejected=page.evaluate("window.desktop.request('https://example.com').then(()=>false,()=>true)");assert rejected
  result['steps'].append('Renderer sandbox/IPC URL boundary')
  page.get_by_role('button',name='调查思维链',exact=True).click()
  expect(page.get_by_role('heading',name='调查思维链',exact=True)).to_be_visible()
  expect(page.get_by_role('heading',name='Planner',exact=True)).to_be_visible()
  expect(page.get_by_role('button',name='导出 Word',exact=True)).to_be_enabled()
  word_data=page.evaluate("async()=>{const js=await window.desktop.request('/investigations');const id=js.find(j=>j.status==='completed').id;return await window.desktop.request('/investigations/'+id+'/report?format=docx')}")
  raw=base64.b64decode(word_data['base64']);(output/'acceptance-report.docx').write_bytes(raw)
  with zipfile.ZipFile(io.BytesIO(raw)) as z:assert '调查思维链' in z.read('word/document.xml').decode()
  page.screenshot(path=str(output/'10-investigation-process.png'))
  result['steps'].append('Investigation execution nodes and actual OOXML Word export from packaged sidecar')
  if pikachu:
   project=page.evaluate("async(path)=>{const rows=await window.desktop.request('/projects');return rows.find(p=>p.name==='Pikachu acceptance')||await window.desktop.request('/projects','POST',{name:'Pikachu acceptance',source:'local',path})}",pikachu['path'])
   page.get_by_role('button',name='代码',exact=True).click();page.get_by_label('代码项目').select_option(project['id'])
   page.get_by_role('button',name='运行扫描',exact=True).click()
   expect(page.get_by_role('button',name='运行扫描',exact=True)).to_be_enabled()
   expect(page.locator('tbody tr').filter(has_text='PHP-SQL-001').filter(has_text='vul/sqli/sqli_str.php')).to_have_count(1)
   page.locator('tbody tr').filter(has_text='PHP-SQL-001').filter(has_text='vul/sqli/sqli_str.php').click()
   expect(page.locator('.inspector')).to_contain_text('CWE-89')
   page.screenshot(path=str(output/'11-pikachu-php.png'))
   result['steps'].append('Actual imported Pikachu PHP source scanned in Windows package; SQL finding at sqli_str.php:29')
  page.get_by_role('button',name='威胁情报',exact=True).click()
  page.get_by_role('button',name='立即同步',exact=True).click()
  expect(page.get_by_role('button',name='立即同步',exact=True)).to_be_enabled(timeout=120000)
  expect(page.locator('tbody tr').first).to_be_visible()
  page.locator('tbody tr').first.click();page.screenshot(path=str(output/'12-intelligence.png'))
  result['intelligence_sync']=page.evaluate("window.desktop.request('/intelligence').then(x=>x.sync.map(s=>({provider:s.id,status:s.status,last_success:s.last_success,error:s.error})))")
  result['steps'].append('Public vulnerability feed sync action, retained SQLite records and intelligence detail UI; live refresh status recorded separately')
  page.get_by_role('button',name='设置',exact=True).click()
  page.get_by_role('button',name='工作与输出目录',exact=True).click()
  expect(page.get_by_label('workspace.working_directory')).to_be_visible()
  page.screenshot(path=str(output/'13-settings-directories.png'))
  result['steps'].append('Settings secondary navigation separates model, XDR, agent, directory and TI configuration')

  result['status']='passed';result['page_errors']=errors
  page.evaluate("setTimeout(()=>window.desktop.windowControl('close'),100)")
except Exception as e:
 result.update(status='failed',error=str(e),page_errors=errors)
 try:
  print(page.locator('body').inner_text()[-4000:])
  print(page.evaluate("window.desktop.request('/investigations').then(x=>x.map(j=>({id:j.id,status:j.status,error:j.error})))"))
  page.screenshot(path=str(output/'failure.png'));page.evaluate("setTimeout(()=>window.desktop.windowControl('close'),100)")
 except Exception:proc.terminate()
finally:
 try:p.stop()
 except Exception:pass
 (output/'result.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf-8');print(json.dumps(result,ensure_ascii=False))
sys.exit(0 if result['status']=='passed' else 1)
